language: cpp

matrix:
  include:
    - os: linux
      dist: xenial
      compiler: gcc
    - os: linux
      dist: xenial
      compiler: clang
    - os: osx
      osx_image: xcode10.1
      compiler: gcc
    - os: osx
      osx_image: xcode10.1
      compiler: clang

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
  homebrew:
    packages:
      - cmake

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh ./tests/travis_setup_linux.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sh ./tests/travis_setup_osx.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then if [ "$CXX" = "g++" ]; then export CXX="g++-7" CC="gcc-7"; fi; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then if [ "$CXX" = "g++" ]; then export CXX="g++-8" CC="gcc-8"; fi; fi

script:
  - sh build.sh
  - sh test.sh