language: cpp

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - cmake-data
  homebrew:
    packages:
      - cmake

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh ./tests/travis_setup_linux.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sh ./tests/travis_setup_osx.sh; fi

jobs:
  include:
    - stage: compile
      name: "Compile"
      script: sh build.sh
    - stage: tests
      name: "Tests"
      script: sh test.sh