language: cpp

os:
  - linux
  - osx

dist: xenial
osx_image: xcode10.1

compiler:
  - gcc
  - clang

addons:
  homebrew:
    packages:
      - cmake

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh ./tests/travis_setup_linux.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sh ./tests/travis_setup_osx.sh; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-7" CC="gcc-7"; fi

script:
  - sh build.sh
  - sh test.sh