version: {build}

os:
  - Visual Studio 2015
  - Visual Studio 2017

configuration: Release

branches:
  only:
  - master
build:
  verbosity: detailed

init: []

install: []

build_script:
  - IF "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2015" ( SET GEN="Visual Studio 14 2015") ELSE (SET GEN="Visual Studio 15 2017")
  - mkdir build
  - cd build
  - cmake . -G%GEN%
  - cmake --build .