version: '1.10.0-{build}'

image:
  - Visual Studio 2017

configuration: Release

environment:
  GEN: Visual Studio 15 2017 Win64

branches:
  only:
  - master
build:
  verbosity: detailed

init:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"

install: []

build_script:
  - cmd: >-
      mkdir build
      cd build
      cmake .. -G"%GEN%"
      cmake --build . --config Release

test_script:
  - cmd: >-
      copy Release\lambdacommon.dll tests\Release
      copy c_wrapper\tests\Release\clambdacommon_test.exe tests\Release
      .\tests\Release\lambdacommon_test.exe
      .\tests\Release\clambdacommon_test.exe